atipugin/telegram-bot-ruby

- lib/telegram/bot/types/contact.rb
- lib/telegram/bot/types/message.rb
- lib/telegram/bot/types/video.rb
Applied July 2015 changes to the Telegram Bot API as detailed in the [Changelog]
(https://core.telegram.org/bots/api-changelog#july-2015).
* The *thumb* field is now optional for `Video`, `Sticker` and `Document` objects
* The API now supports both video and photo captions. The *caption* field has been removed from the `Video` object and added to the `Message` object instead.
* *caption* and *duration* optional fields have been added to the `sendVideo` method.
* Fixed typo: *user_id* in the `Contact` object is now correctly labeled as `Integer`, not `String`
> Bot API changes from July 2015

- README.md
- examples/bot.rb
- lib/telegram/bot/api.rb
CamelCase methods like ```bot.api.sendMessage```contradict the [Ruby style guide] (https://github.com/bbatsov/ruby-style-guide). I've added support of snake_case for method_missing in Api class.
> use snake_case for api methods

- lib/telegram/bot/exceptions/response_error.rb
This addresses Issue #20. Accessing both the symbol name and string is necessary, since the fallback from the JSON failing to be parsed uses the symbol `:error_code`, but the actual JSON key is a string.
> expose error_code in ResponseError

- lib/telegram/bot/client.rb
Hi,
`message.from` can be nil (https://core.telegram.org/bots/api#message).
In that case the gem throws an exception.
I've found basic specs only. Should I write a spec for this case?
> Fixed fail on empty from field

- lib/telegram/bot/client.rb
- spec/lib/telegram/bot/client_spec.rb
Hello!
What about accepting any option on `Telegram::Bot::Client.new`, so we don't have to update the code at each telegram `getUpdates` change?
For example `allowed_updates` and `limit` options are missing at the moment... https://core.telegram.org/bots/api#getupdates
> better client options handling

- lib/telegram/bot/api.rb
Close #89.
According to Bot API 2.3.1 [CHANGELOG](https://core.telegram.org/bots/api-changelog#december-4-2016):
> deleteWebhook moved out of setWebhook to get a whole separate method for itself.
> Add deleteWebhook method

- lib/telegram/bot/client.rb
When bot added to channel bot crashed with error 
`/usr/local/rvm/gems/ruby-2.3.3/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:59:in 'log_incoming_message': undefined method 'from' for nil:NilClass (NoMethodError)`
That was because Types::Update now can have new fields: channel_post, edited_channel_post (like it was described in issue #82)
After changes made here my bot works correctly in channels
> fix bug with getting message

- CHANGELOG.md
@atipugin we can use this syntax to avoid duplication of links to contributor profiles in Changelog.
> Describe contributor links in Changelog's bottom

- lib/telegram/bot.rb
- lib/telegram/bot/types.rb
- lib/telegram/bot/types/base.rb
- lib/telegram/bot/types/chat.rb
- lib/telegram/bot/types/compactable.rb
- lib/telegram/bot/types/message.rb
- lib/telegram/bot/types/user.rb
- telegram-bot-ruby.gemspec
Hi @atipugin,
I have made [Bot API 3.3](https://core.telegram.org/bots/api-changelog#august-23-2017) updates.
This one is tricky. Now we have a circular dependency between `Chat` and `Message`.
I found Virtus [documentation](https://github.com/solnic/virtus/blob/master/README.md#attribute-finalization-and-circular-dependencies) about that.
However Virtus complains about namespaced types,
> Virtus needs inflecto gem to constantize namespaced constant names (NotImplementedError)
so we should use `inflecto` 😐 
I have tested it in console, it seems to work fine.
> Implement Bot API 3.3

- lib/telegram/bot/types.rb
- lib/telegram/bot/types/input_media_photo.rb
- lib/telegram/bot/types/input_media_video.rb
Hi @atipugin,
This one fixes #163 by adding `require`.
Also it adds default type value for `Types::InputMedia` to allow to skip `type` attribute in constructor.
> Bot API 3.5 updates

- lib/telegram/bot/types/message.rb
Hello! Thank u for awesome gem.
I found some problem with implemented attributes list of message object.
- `media_group_id` string attribute was missed in `telegram-bot-ruby/lib/telegram/bot/types/message.rb`.
My PR solves this problem.
> Missed media_group_id attr for Message object was added

- lib/telegram/bot/types.rb
- lib/telegram/bot/types/base.rb
- lib/telegram/bot/types/chat.rb
- lib/telegram/bot/types/pattern_matching.rb
This PR adds support for [pattern-matching](https://docs.ruby-lang.org/en/3.0.0/doc/syntax/pattern_matching_rdoc.html) Telegram types.
Some silly example:
```rb
update = Telegram::Bot::Api::Update.new(payload)
include Telegram::Bot::Api::Types
case update
in Update(message: Message(text: text, from: User(id: telegram_id, is_bot: false)))
bot.api.send_message(chat_id: telegram_id, text: text.reverse)
in Update(message: Message(text: text, from: User(id: telegram_id, is_bot: true)))
bot.api.send_message(chat_id: telegram_id, text: 'No bots allowed!')
else
end
```
> Add pattern matching support for Telegram types

- lib/telegram/bot/types/compactable.rb
The current implementation of `Compactable#to_compact_hash` checks if a value inherits from `Types::Base`, which unfortunately is not the case for `Types::Chat`. So when we call `#to_compact_hash` for any `Types::Base` object that recursively contains a `Types::Chat` object, all values except for the chat object are converted to hash.
```rb
update = Telegram::Bot::Types::Update.new(message: { chat: { id: 1 }, text: '/start' })
puts update.to_compact_hash
```
The whole update is recursively converted to hash:
```rb
{:message=>{:chat=>{:id=>1}, :text=>"/start", :entities=>[], :caption_entities=>[], :photo=>[], :new_chat_members=>[], :new_chat_photo=>[]}
```
The following hash is printed (note that `:chat` is not converted to hash):
```rb …
```
> Call #to_compact_hash on all objects responding to it

- lib/telegram/bot/api.rb
- lib/telegram/bot/client.rb
- lib/telegram/bot/configuration.rb
- spec/lib/telegram/bot/api_spec.rb
It looks like current gem logic does not allow global timeout configuration.
Now user can set timeouts only for each request separately. 
And timeout for Telegram::Bot::Client works only for getUpdates requests.
In current implementation timeout for getUpdates request does not changed by default.
I hope it will be useful for global telegram bot configuration.
> Global timeout configuration

- README.md
- lib/telegram/bot/api.rb
- lib/telegram/bot/client.rb
- spec/lib/telegram/bot/api_spec.rb
- spec/lib/telegram/bot/client_spec.rb
Hi. I added the support of environments to  bots.
This required for  developing Web Applications if you want to run it without ssl.
More info here: https://core.telegram.org/bots/webapps#testing-web-apps
I moved your token to ENV variable.
You can run test with help this command:
`BOT_API_TOKEN=<TOKEN>  bundle exec rspec spec`
> Added Test environment

- Rakefile
- bin/console
- spec/spec_helper.rb
- telegram-bot-ruby.gemspec
It also can prevent some errors with requiring not proper version from specs (but globally installed one).
> Use `require_relative` instead of `File.expand_path` and `$LOAD_PATH.unshift`

- .rubocop.yml
- Gemfile
- Rakefile
- bin/console
- lib/telegram/bot/types/compactable.rb
1. Lock its version better (new minor versions with `NewCops: enable` give new offenses).
2. Fix some new offenses.
3. Add performance plugin.
> Improve RuboCop

- lib/telegram/bot/api.rb
- lib/telegram/bot/exceptions/response_error.rb
- spec/lib/telegram/bot/api_spec.rb
- spec/lib/telegram/bot/exceptions/response_error_spec.rb
* Make `ResponseError#data` public.
It's useful for checks by fields inside `rescue`, re-raise or not.
* Remake specs of `ResponseError#error_code`.
* Add specs for `ResponseError#to_s`.
* Replace double quotes for any value inside `ResponseError#to_s` with `.inspect`:
now the type of value is more obvious (Boolean, Integer, String, etc.).
* Improve `ResponseError` initialization.
Don't expect basic message, have it inside the class.
> Improve `ResponseError`

- lib/telegram/bot/api.rb
I see no reason to shrink it's like this.
Also I'm thinking to make it's public:
can be helpful for adding middlewares, such as `:logger`, but maybe I'll consider changes to the `Bot::Configuration` later.
---
Update: I've decided to make it public, because don't know how to add `connection.response :logger, nil, { headers: true, bodies: true }` into `Configuration` with flexible customization. It seems just easier to call `connection` from outside as you want.
> Rename `Bot::Api#conn` to `#connection` and make it public

- .rspec
It's useful to detect Ruby warnings, some coming changes. (Fortunatelly, there are no warnings for now)
> Enable Ruby warnings for RSpec

- README.md
- lib/telegram/bot/client.rb
- spec/lib/telegram/bot/client_spec.rb
1. Add an ability to stop bot's infinity loop from outside.
2. Remove `exit` which kills any (parent) process with a bot, like specs.
> Add `Bot::Client#stop` method

- lib/telegram/bot/client.rb
- spec/lib/telegram/bot/client_spec.rb
Current version gets stuck in a loop of reconnections if the bot does not receive any messages even though it received `#stop`
> Fix infinite loop on Timeout while stopped

- data/type_attributes.json
- lib/telegram/bot/types/affiliate_info.rb
- lib/telegram/bot/types/star_transaction.rb
- lib/telegram/bot/types/transaction_partner.rb
- lib/telegram/bot/types/transaction_partner_affiliate_program.rb
- lib/telegram/bot/types/transaction_partner_user.rb
See: https://core.telegram.org/bots/api-changelog#october-31-2024
> Implement Bot API 8.1

- CHANGELOG.md
Seems like Telegram changes links format a little bit, so older links do not work properly
I've checked most of them after the fix - all seems good
> Fix changelog to have correct links
